from rest_framework.routers import DefaultRouter
from apirest.views import *

router_apirest = DefaultRouter()

# Routes
router_apirest.register(prefix='ActionShape', basename='ActionShape', viewset=ActionShape)
router_apirest.register(prefix='Actions', basename='Actions', viewset=Actions)
router_apirest.register(prefix='Attachments', basename='Attachments', viewset=Attachments)
router_apirest.register(prefix='Backups', basename='Backups', viewset=Backups)
router_apirest.register(prefix='Capsules', basename='Capsules', viewset=Capsules)
router_apirest.register(prefix='Categories', basename='Categories', viewset=Categories)
router_apirest.register(prefix='DetailsProgress', basename='DetailsProgress', viewset=DetailsProgress)
router_apirest.register(prefix='EquipmentTechnicalObject', basename='EquipmentTechnicalObject', viewset=EquipmentTechnicalObject)
router_apirest.register(prefix='EquipmentVirtualPlant', basename='EquipmentVirtualPlant', viewset=EquipmentVirtualPlant)
router_apirest.register(prefix='Equipments', basename='Equipments', viewset=Equipments)
router_apirest.register(prefix='ExamQuestion', basename='ExamQuestion', viewset=ExamQuestion)
router_apirest.register(prefix='ExamQuestionParents', basename='ExamQuestionParents', viewset=ExamQuestionParents)
router_apirest.register(prefix='ExamResults', basename='ExamResults', viewset=ExamResults)
router_apirest.register(prefix='ExamTypes', basename='ExamTypes', viewset=ExamTypes)
router_apirest.register(prefix='Exams', basename='Exams', viewset=Exams)
router_apirest.register(prefix='FailedJobs', basename='FailedJobs', viewset=FailedJobs)
router_apirest.register(prefix='Files', basename='Files', viewset=Files)
router_apirest.register(prefix='Historicals', basename='Historicals', viewset=Historicals)
router_apirest.register(prefix='Icons', basename='Icons', viewset=Icons)
router_apirest.register(prefix='Images', basename='Images', viewset=Images)
router_apirest.register(prefix='Interlug', basename='Interlug', viewset=Interlug)
router_apirest.register(prefix='Jobs', basename='Jobs', viewset=Jobs)
router_apirest.register(prefix='Levels', basename='Levels', viewset=Levels)
router_apirest.register(prefix='MapShape', basename='MapShape', viewset=MapShape)
router_apirest.register(prefix='MapTypes', basename='MapTypes', viewset=MapTypes)
router_apirest.register(prefix='Maps', basename='Maps', viewset=Maps)
router_apirest.register(prefix='Migrations', basename='Migrations', viewset=Migrations)
router_apirest.register(prefix='Options', basename='Options', viewset=Options)
router_apirest.register(prefix='PasswordResets', basename='PasswordResets', viewset=PasswordResets)
router_apirest.register(prefix='PermissionRole', basename='PermissionRole', viewset=PermissionRole)
router_apirest.register(prefix='Permissions', basename='Permissions', viewset=Permissions)
router_apirest.register(prefix='PlantItem', basename='PlantItem', viewset=PlantItem)
router_apirest.register(prefix='PlantItemFile', basename='PlantItemFile', viewset=PlantItemFile)
router_apirest.register(prefix='Procedures', basename='Procedures', viewset=Procedures)
router_apirest.register(prefix='Progress', basename='Progress', viewset=Progress)
router_apirest.register(prefix='QuestionLevels', basename='QuestionLevels', viewset=QuestionLevels)
router_apirest.register(prefix='QuestionResults', basename='QuestionResults', viewset=QuestionResults)
router_apirest.register(prefix='Questions', basename='Questions', viewset=Questions)
router_apirest.register(prefix='RoleUser', basename='RoleUser', viewset=RoleUser)
router_apirest.register(prefix='Roles', basename='Roles', viewset=Roles)
router_apirest.register(prefix='ScoreDetails', basename='ScoreDetails', viewset=ScoreDetails)
router_apirest.register(prefix='Scores', basename='Scores', viewset=Scores)
router_apirest.register(prefix='Sessions', basename='Sessions', viewset=Sessions)
router_apirest.register(prefix='Shapes', basename='Shapes', viewset=Shapes)
router_apirest.register(prefix='TechnicalObjectFile', basename='TechnicalObjectFile', viewset=TechnicalObjectFile)
router_apirest.register(prefix='TechnicalObjects', basename='TechnicalObjects', viewset=TechnicalObjects)
router_apirest.register(prefix='Troubleshooting', basename='Troubleshooting', viewset=Troubleshooting)
router_apirest.register(prefix='Users', basename='Users', viewset=Users)
router_apirest.register(prefix='Versions', basename='Versions', viewset=Versions)
router_apirest.register(prefix='VirtualPlants', basename='VirtualPlants', viewset=VirtualPlants)
router_apirest.register(prefix='WebsocketsStatisticsEntries', basename='WebsocketsStatisticsEntries', viewset=WebsocketsStatisticsEntries)